<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Report - {{ $chat->title ?? 'Untitled' }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .header {
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #1a1a1a;
        }

        .header .meta {
            margin-top: 10px;
            font-size: 11px;
            color: #666;
        }

        .message {
            margin-bottom: 20px;
            padding: 15px;
            border-left: 4px solid #ddd;
            background-color: #f9f9f9;
        }

        .message.user {
            border-left-color: #3b82f6;
            background-color: #eff6ff;
        }

        .message.assistant {
            border-left-color: #10b981;
            background-color: #f0fdf4;
        }

        .message-header {
            font-weight: bold;
            margin-bottom: 8px;
            font-size: 13px;
            color: #555;
        }

        .message.user .message-header {
            color: #1e40af;
        }

        .message.assistant .message-header {
            color: #065f46;
        }

        .message-content {
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .message-footer {
            margin-top: 8px;
            font-size: 10px;
            color: #888;
        }

        .agent-info {
            font-size: 10px;
            color: #666;
            margin-top: 5px;
        }

        .footer {
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #888;
            text-align: center;
        }

        .section-divider {
            margin: 30px 0;
            border-top: 1px solid #ddd;
        }

        .workflow-info {
            background-color: #f3f4f6;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 20px;
            font-size: 11px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $chat->title ?? 'Chat Report' }}</h1>
        <div class="meta">
            <div><strong>Suite:</strong> {{ $chat->suite->name ?? 'N/A' }}</div>
            @if($chat->agent)
                <div><strong>Agent:</strong> {{ $chat->agent->name }}</div>
            @endif
            @if($chat->workflow)
                <div><strong>Workflow:</strong> {{ $chat->workflow->name }}</div>
            @endif
            <div><strong>Generated:</strong> {{ now()->format('F d, Y \a\t H:i:s') }}</div>
            <div><strong>Total Messages:</strong> {{ $messages->count() }}</div>
        </div>
    </div>

    @if($chat->workflow)
        <div class="workflow-info">
            <strong>Workflow Execution:</strong> This report contains the final output from a multi-agent workflow.
            @if($chat->workflow->agent_sequence)
                <br>Agent Sequence: {{ count($chat->workflow->agent_sequence) }} agents
            @endif
        </div>
    @endif

    <div class="messages">
        @foreach($messages as $message)
            <div class="message {{ $message->role }}">
                <div class="message-header">
                    {{ ucfirst($message->role) }}
                    @if($message->agent)
                        <span class="agent-info">(Agent: {{ $message->agent->name }})</span>
                    @endif
                </div>
                <div class="message-content">{{ $message->content }}</div>
                <div class="message-footer">
                    {{ $message->created_at->format('M d, Y H:i:s') }}
                    @if($message->metadata && isset($message->metadata['model']))
                        | Model: {{ $message->metadata['model'] }}
                    @endif
                    @if($message->metadata && isset($message->metadata['tokens_used']))
                        | Tokens:
                        {{ ($message->metadata['tokens_used']['input'] ?? 0) + ($message->metadata['tokens_used']['output'] ?? 0) }}
                    @endif
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        <p>Generated by AI Control Hub</p>
        <p>This report contains {{ $messages->count() }} message(s) from the chat session.</p>
    </div>
</body>

</html>



